#!/bin/bash
cd "$(dirname "$0")"
source ./script/setup.sh

# Identity/team detection is shared with build-release.sh -- see script/signing-identity.sh.
source ./script/signing-identity.sh

export XCODEGEN_AEROSPORK_CODE_SIGN_IDENTITY="${XCODEGEN_AEROSPORK_CODE_SIGN_IDENTITY:-$(default_signing_identity)}"

export XCODEGEN_AEROSPORK_DEVELOPMENT_TEAM="${XCODEGEN_AEROSPORK_DEVELOPMENT_TEAM:-$(
    default_development_team "$XCODEGEN_AEROSPORK_CODE_SIGN_IDENTITY"
)}"

# A PLACEHOLDER, not the current release, and deliberately not bumped per release. It is the
# value baked into Sources/Common/versionGenerated.swift, which is checked in, and `run-tests.sh`
# runs `generate.sh --all` and then fails on a dirty tree -- so the committed file has to equal
# whatever this produces with no arguments. Committing a real release version here (say after
# cutting 1.1.1) looks like it corrects a stale file and instead breaks the gate on the next run.
# Release builds pass --build-version, so what ships is always the real version regardless.
build_version="1.0.0"
generate_xcodeproj=1
all=0
while test $# -gt 0; do
    case $1 in
        --build-version) build_version="$2"; shift 2 ;;
        --codesign-identity) XCODEGEN_AEROSPORK_CODE_SIGN_IDENTITY="$2"; shift 2 ;;
        --ignore-xcodeproj) generate_xcodeproj=0; shift 1 ;;
        --all) all=1; shift 1 ;;
        *) echo "Unknown option $1"; exit 1 ;;
    esac
done

if test $all = 1 && test $generate_xcodeproj = 0; then
    echo "./generate.sh: --all and --ignore-xcodeproj are conflicting" > /dev/stderr
    exit 1
fi

if test $all = 1; then
    # It takes 300ms for script to complete. It's too long to run in build-debug.sh
    ./script/generate-cmd-help.sh
fi

cat > Sources/Common/versionGenerated.swift <<EOF
// FILE IS GENERATED BY generate.sh
public let aeroSporkAppVersion = "$build_version"
EOF

entries() {
    for file in docs/aerospork-*.adoc; do
        if grep -q 'exec-and-forget' <<< $file; then
            continue
        fi
        subcommand=$(basename $file | sed 's/^aerospork-//' | sed 's/\.adoc$//')
        desc="$(grep :manpurpose: "$file" | sed -E 's/:manpurpose: //')"
        echo "    [\"  $subcommand\", \"$desc\"],"
    done
}

cat <<EOF > ./Sources/Cli/subcommandDescriptionsGenerated.swift
// FILE IS GENERATED FROM docs/aerospork-*.adoc files
// TO REGENERATE THE FILE RUN generate.sh

let subcommandDescriptions = [
$(entries)
]
EOF

cat <<EOF > ./Sources/Common/gitHashGenerated.swift
// FILE IS GENERATED BY generate.sh AND AUTO-UPDATED BY build-release.sh
public let gitHash = "SNAPSHOT"
public let gitShortHash = "SNAPSHOT"
EOF

if test $generate_xcodeproj = 1; then
    export XCODEGEN_AEROSPORK_VERSION=$build_version
    ./script/install-dep.sh --xcodegen
    ./.deps/xcodegen/xcodegen # https://github.com/yonaskolb/XcodeGen
fi
