# Xcode project configuration. Managed by https://github.com/yonaskolb/XcodeGen
# Xcode is only used to build the release App Bundle. Debug builds only use Swift Package Manager

name: j4

packages:
  j4Package:
    path: .

configs:
  Debug: debug
  Release: release

targets:
  j4:
    type: application
    platform: macOS
    deploymentTarget: "13.0"
    sources:
      - "Sources/j4App"
      - "resources"
    dependencies:
      - package: j4Package
        product: AppBundle
    # https://developer.apple.com/documentation/xcode/build-settings-reference
    settings:
      base:
        SWIFT_VERSION: 6.0
        GENERATE_INFOPLIST_FILE: YES
        MARKETING_VERSION: ${XCODEGEN_AEROSPORK_VERSION}
        CURRENT_PROJECT_VERSION: 1
        # https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/LaunchServicesKeys.html#//apple_ref/doc/uid/20001431-108256
        # Specifies whether the app runs as an agent app. If this key is set to YES, Launch Services runs the app as an agent app.
        # Agent apps do not appear in the Dock or in the Force Quit window
        INFOPLIST_KEY_LSUIElement: YES
        CODE_SIGN_IDENTITY: "-"
        CODE_SIGN_STYLE: Manual
        # App Store submission requirements
        ENABLE_HARDENED_RUNTIME: YES
        INFOPLIST_KEY_LSApplicationCategoryType: public.app-category.productivity
        INFOPLIST_KEY_NSHumanReadableCopyright: "Copyright © 2025 j4. All rights reserved."
        # App icon
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
      configs:
        Debug:
          PRODUCT_NAME: j4-Debug
          PRODUCT_BUNDLE_IDENTIFIER: com.wbs.j4.debug
        Release:
          PRODUCT_NAME: j4
          PRODUCT_BUNDLE_IDENTIFIER: com.wbs.j4
    entitlements:
      path: resources/j4.entitlements
      properties:
        com.apple.security.app-sandbox: true
        com.apple.security.automation.apple-events: true
        com.apple.security.temporary-exception.apple-events: com.apple.systemevents
