#!/bin/bash
cd "$(dirname "$0")/.."
source ./script/setup.sh

zip_uri='' # mandatory
cask_name='' # mandatory
build_version="0.0.0-SNAPSHOT"
# Must match what build-release.sh actually packs. publish-release.sh calls this script without
# --app-bundle-dir-name, and the old default ('AeroSpork.app') produced a cask that pointed at a
# path the zip does not contain -- invisible on case-insensitive APFS, a 404 everywhere else.
app_bundle_dir_name='AeroSpork.app'
while test $# -gt 0; do
    case $1 in
        --build-version) build_version="$2"; shift 2;;
        --zip-uri) zip_uri="$2"; shift 2;;
        --app-bundle-dir-name) app_bundle_dir_name="$2"; shift 2;;
        --cask-name) cask_name="$2"; shift 2;;
        *) echo "Unknown arg $1"; exit 1;;
    esac
done

if test -z "$zip_uri"; then echo "--zip-uri is mandatory" > /dev/stderr; exit 1; fi
if test -z "$cask_name"; then echo "--cask-name is mandatory" > /dev/stderr; exit 1; fi

case "$cask_name" in
    aerospork) conflicts_with_casks="  conflicts_with cask: \"aerospork-dev\"";;
    aerospork-dev) conflicts_with_casks="  conflicts_with cask: \"aerospork\"";;
    *) echo "Unknown cask name: $cask_name. Allowed cask names: aerospork, aerospork-dev" > /dev/stderr; exit 1;;
esac

zip_file=''
if test -f "$zip_uri"; then
    zip_file=$zip_uri
    zip_uri="file://$(realpath "$zip_file")"
elif grep -q '^http' <<< "$zip_uri"; then
    zip_file=/tmp/AeroSpork-tmp.zip
    rm -rf $zip_file
    curl -L "$zip_uri" -o $zip_file
else
    echo "$zip_uri doesn't exist" > /dev/stderr; exit 1
fi
sha=$(shasum -a 256 "$zip_file" | awk '{print $1}')

cask_version=':latest' # Prevent 'Not upgrading aerospork, the latest version is already installed'
zip_root_dir="aerospork-v$build_version"
if ! grep -q SNAPSHOT <<< "$build_version"; then
    # Double quotes, not single: `brew style` (RuboCop Style/StringLiterals) rejects single-quoted
    # strings in casks, and a tap that does not pass `brew style` is one Homebrew will not take.
    cask_version="\"$build_version\""
    zip_root_dir=$(sed "s/$build_version/#{version}/g" <<< "$zip_root_dir")
    zip_uri=$(sed "s/$build_version/#{version}/g" <<< "$zip_uri")
fi

manpages=$(unzip -l "$zip_file" | \
    grep --only-matching 'manpage/aerospork.*' | \
    while read -r it; do echo "  manpage \"$zip_root_dir/$it\""; done | \
    sort)

rm -f ".release/$cask_name.rb" || true
mkdir -p .release
cat > ".release/$cask_name.rb" <<EOF
cask "$cask_name" do # THE FILE IS GENERATED BY build-brew-cask.sh
  version $cask_version
  sha256 "$sha"

  url "$zip_uri"
  name "AeroSpork"
  # \`brew style\` (Cask/Desc) rejects a desc that opens with the cask name, opens with an article,
  # or names the platform -- so not "AeroSpork is an i3-like tiling window manager for macOS",
  # which is how the prose reads everywhere else. Homebrew already shows the name and the platform.
  desc "Tiling window manager with i3-like tree layout"
  homepage "https://github.com/wbsmolen/aerospork"

$conflicts_with_casks
  # \`macos: :ventura\` is the MINIMUM, not an exact match -- Homebrew's OSDependsOn cop rewrites
  # ">= :ventura" to exactly this, so the two are the same requirement.
  depends_on macos: :ventura # macOS 13

  # No quarantine-stripping postflight. It used to run
  #   xattr -d com.apple.quarantine ...
  # which Homebrew rejects in submitted casks, and which did nothing for anyone downloading the
  # zip directly — it only worked because brew happened to run it locally. The real fix is
  # notarization (see build-release.sh), which makes Gatekeeper accept the app on any Mac.

  app "$zip_root_dir/$app_bundle_dir_name"
  # The CLI is shipped INSIDE the app bundle, and this points at the installed copy rather than at
  # the zip's bin/ (which is only a symlink into the same place). A standalone copy on disk would be
  # a bare Mach-O, and a notarization ticket cannot be stapled to one of those -- Apple's own
  # \`syspolicy_check distribution\` calls that "Notary Ticket Missing ... Severity: Fatal". Inside
  # the bundle it is covered by the app's stapled ticket and works with no network.
  binary "#{appdir}/$app_bundle_dir_name/Contents/MacOS/aerospork-cli", target: "aerospork"
  # \`target:\` lines align under the first argument (Layout/ArgumentAlignment), not at a fixed
  # indent.
  binary "$zip_root_dir/shell-completion/zsh/_aerospork",
         target: "#{HOMEBREW_PREFIX}/share/zsh/site-functions/_aerospork"
  binary "$zip_root_dir/shell-completion/bash/aerospork",
         target: "#{HOMEBREW_PREFIX}/etc/bash_completion.d/aerospork"
  binary "$zip_root_dir/shell-completion/fish/aerospork.fish",
         target: "#{HOMEBREW_PREFIX}/share/fish/vendor_completions.d/aerospork.fish"
$manpages
end
EOF
