= aerospork-focus(1)
include::util/man-attributes.adoc[]
:manname: aerospork-focus
// tag::purpose[]
:manpurpose: Set focus to the nearest window in the given direction
// end::purpose[]

// =========================================================== Synopsis
== Synopsis
[verse]
// tag::synopsis[]
aerospork focus [-h|--help] [--ignore-floating]
                [--boundaries <boundary>] [--boundaries-action <action>]
                (left|down|up|right)
aerospork focus [-h|--help] --window-id <window-id>
aerospork focus [-h|--help] --dfs-index <dfs-index>

// end::synopsis[]

// =========================================================== Description
== Description

// tag::body[]
{manpurpose}

Unlike i3, `focus` has no separate argument for floating windows.
It treats them as part of xref:guide.adoc#floating-windows[the tree], which removes the need for a
separate binding.
Pass `--ignore-floating` to turn that off.

`focus child|parent` is not supported.

// =========================================================== Options
include::util/conditional-options-header.adoc[]

-h, --help:: Print help

--boundaries <boundary>::
Defines focus boundaries. +
`<boundary>` possible values: `(workspace|all-monitors-outer-frame)`. +
The default is: `workspace`

--boundaries-action <action>::
Defines the behavior when requested to cross the `<boundary>`. +
`<action>` possible values: `(stop|fail|wrap-around-the-workspace|wrap-around-all-monitors)` +
The default is: `stop`

--window-id <window-id>::
Focus the window with specified `<window-id>`

--dfs-index <dfs-index>::
Focus window by its index, based on a depth-first search (DFS) of the window within the workspace tree.
Index is 0-based.

--ignore-floating::
Don't treat floating windows as part of the tree.
Useful for more predictable scripting.

// end::body[]

// =========================================================== Footer
include::util/man-footer.adoc[]
