= AeroSpork Goodies
include::util/site-attributes.adoc[]

include::util/header.adoc[]

Have an automation, integration, or workflow worth sharing?
Open an issue or pull request to add it to this list.
The source of this page is in the `./docs` directory.

[#move-by-dragging-any-part-of-the-window]
== Move windows by dragging any part of the window

[source,bash]
----
defaults write -g NSWindowShouldDragOnGesture -bool true
----

Windows can then be moved by holding `ctrl + cmd` and dragging any part of the window, not only the title bar.

[#highlight-focused-windows-with-colored-borders]
== Highlight focused windows with colored borders

link:https://github.com/FelixKratz/JankyBorders[JankyBorders] draws a colored border around the focused window.

`after-startup-command` can start it together with AeroSpork:

[source,toml]
----
after-startup-command = [
    # JankyBorders has a built-in detection of already running process,
    # so it won't be run twice on AeroSpork restart
    'exec-and-forget borders active_color=0xffe1e3e4 inactive_color=0xff494d64 width=5.0'
]
----

[#raycast-extension]
== Raycast extension

A third party Raycast extension exists for upstream AeroSpace: https://www.raycast.com/limonkufu/aerospace

It drives the `aerospace` binary, so the command name has to be changed to `aerospork` to work here.
It lets you search for commands by name instead of recalling their shortcuts.

[#disable-open-animations]
== Disable windows opening animations

Observable in Google Chrome

[source,bash]
----
defaults write -g NSAutomaticWindowAnimationsEnabled -bool false
----

[#use-trackpad-gestures-to-switch-workspaces]
== Use trackpad gestures to switch workspaces

These commands focus the next or previous workspace on the monitor the mouse is on:

[source,bash]
----
aerospork workspace "$(aerospork list-workspaces --monitor mouse --visible)" && aerospork workspace next

aerospork workspace "$(aerospork list-workspaces --monitor mouse --visible)" && aerospork workspace prev
----

Use the software of your choice to assign trackpad gestures to the respective commands.
A few third party options, in alphabetical order. All of them were written for upstream AeroSpace, so
they invoke the `aerospace` binary and read `AEROSPACE_*` environment variables; both need adjusting
for AeroSpork:

* https://github.com/acsandmann/aerospace-swipe
* link:https://folivora.ai/[BetterTouchTool] can assign arbitrary commands to trackpad gestures.
Beware that you might need to specify full path to aerospork executable https://community.folivora.ai/t/how-to-execute-terminal-command-to-switch-workspaces-with-aerospace/35914
* https://github.com/MediosZ/SwipeAeroSpace

CAUTION: Make sure you trust the project authors before running a distributed binary.
Otherwise, inspect the source and build it yourself.

[#show-aerospork-workspaces-in-sketchybar]
== Show AeroSpork workspaces in Sketchybar

AeroSpork workspace indicators can be driven from link:https://github.com/FelixKratz/SketchyBar[Sketchybar].
Use these snippets as a starting point.

.~/.aerospork.toml
[source,toml]
----
# Run Sketchybar together with AeroSpork
# sketchbar has a built-in detection of already running process,
# so it won't be run twice on AeroSpork restart
after-startup-command = ['exec-and-forget sketchybar']

# Notify Sketchybar about workspace change
exec-on-workspace-change = ['/bin/bash', '-c',
    'sketchybar --trigger aerospork_workspace_change FOCUSED_WORKSPACE=$AEROSPORK_FOCUSED_WORKSPACE'
]
----

.~/.config/sketchybar/sketchybarrc
[source,bash]
----
sketchybar --add event aerospork_workspace_change

for sid in $(aerospork list-workspaces --all); do
    sketchybar --add item space.$sid left \
        --subscribe space.$sid aerospork_workspace_change \
        --set space.$sid \
        background.color=0x44ffffff \
        background.corner_radius=5 \
        background.height=20 \
        background.drawing=off \
        label="$sid" \
        click_script="aerospork workspace $sid" \
        script="$CONFIG_DIR/plugins/aerospork.sh $sid"
done
----

.~/.config/sketchybar/plugins/aerospork.sh
[source,bash]
----
#!/usr/bin/env bash

# make sure it's executable with:
# chmod +x ~/.config/sketchybar/plugins/aerospork.sh

if [ "$1" = "$FOCUSED_WORKSPACE" ]; then
    sketchybar --set $NAME background.drawing=on
else
    sketchybar --set $NAME background.drawing=off
fi
----

[#open-a-new-window-with-applescript]
== Open a new window with AppleScript

`exec-and-forget open -a Safari` does not open a new window.
It brings into focus whichever workspace already contains a Safari window.

To open *a new window* of a program that supports multiple windows (Safari, Terminal.app), inline an AppleScript in `aerospork.toml`:

- Safari
+
[source,toml]
----
[mode.main.binding]
ctrl-g = '''exec-and-forget osascript -e '
tell application "Safari"
    make new document at end of documents
    activate
end tell'
'''
----
- Terminal
+
[source,toml]
----
[mode.main.binding]
ctrl-g = '''exec-and-forget osascript -e '
tell application "Terminal"
    do script
    activate
end tell'
'''
----

[#disable-hide-app]
== Disable the "hide application" shortcut

If `automatically-unhide-macos-hidden-apps` isn't enough, disable `cmd-h` altogether.
The hotkey then becomes unavailable to apps that use it for something else.

.~/.aerospork.toml
[source,toml]
----
[mode.main.binding]
    cmd-h = [] # Disable "hide application"
    cmd-alt-h = [] # Disable "hide others"
----

[#screenshoot-shortcut]
== Take a screenshot to the clipboard with a keyboard shortcut

Bind a shortcut to `screencapture`, a built-in macOS command.

.~/.aerospork.toml
[source,toml]
----
[mode.main.binding]
alt-shift-s = 'exec-and-forget screencapture -i -c'
----

[#i3-like-config]
== i3-like config

link:config-examples/i3-like-config-example.toml[Download i3-like-config.toml]

[source,toml,subs="macros+,specialchars+"]
----
include::config-examples/i3-like-config-example.toml[]
----

[#popular-apps-ids]
== Application IDs of popular and built-in apps

Use these to write an xref:guide.adoc#on-window-detected-callback[on-window-detected callback].

[cols="1,3"]
|===
|Application name|Application ID

|1Password|`com.1password.1password`
|Activity Monitor|`com.apple.ActivityMonitor`
|AirPort Utility|`com.apple.airport.airportutility`
|Alacritty|`org.alacritty`
|Android Studio|`com.google.android.studio`
|App Store|`com.apple.AppStore`
|AppCode|`com.jetbrains.AppCode`
|Arc Browser|`company.thebrowser.Browser`
|Audio MIDI Setup|`com.apple.audio.AudioMIDISetup`
|Automator|`com.apple.Automator`
|Battle.net|`net.battle.app`
|Books|`com.apple.iBooksX`
|Brave|`com.brave.Browser`
|Calculator|`com.apple.calculator`
|Calendar|`com.apple.iCal`
|Chess|`com.apple.Chess`
|CLion|`com.jetbrains.CLion`
|Clock|`com.apple.clock`
|ColorSync Utility|`com.apple.ColorSyncUtility`
|Console|`com.apple.Console`
|Contacts|`com.apple.AddressBook`
|Dictionary|`com.apple.Dictionary`
|Disk Utility|`com.apple.DiskUtility`
|Docker|`com.docker.docker`
|FaceTime|`com.apple.FaceTime`
|Figma|`com.figma.Desktop`
|Find My|`com.apple.findmy`
|Finder|`com.apple.finder`
|Firefox|`org.mozilla.firefox`
|Freeform|`com.apple.freeform`
|Ghostty|`com.mitchellh.ghostty`
|GIMP|`org.gimp.gimp-2.10`
|Google Chrome|`com.google.Chrome`
|Grapher|`com.apple.grapher`
|Home|`com.apple.Home`
|iMovie|`com.apple.iMovieApp`
|Inkscape|`org.inkscape.Inkscape`
|IntelliJ IDEA Community|`com.jetbrains.intellij.ce`
|IntelliJ IDEA Ultimate|`com.jetbrains.intellij`
|iTerm2|`com.googlecode.iterm2`
|Karabiner-Elements|`org.pqrs.Karabiner-Elements.Settings`
|kdenlive|`org.kde.Kdenlive`
|Keychain Access|`com.apple.keychainaccess`
|Keynote|`com.apple.iWork.Keynote`
|Kitty|`net.kovidgoyal.kitty`
|Mail|`com.apple.mail`
|Maps|`com.apple.Maps`
|Marta|`org.yanex.marta`
|Messages|`com.apple.MobileSMS`
|Music|`com.apple.Music`
|Notes|`com.apple.Notes`
|Obsidian|`md.obsidian`
|Pages|`com.apple.iWork.Pages`
|Photo Booth|`com.apple.PhotoBooth`
|Photos|`com.apple.Photos`
|Podcasts|`com.apple.podcasts`
|Preview|`com.apple.Preview`
|PyCharm Community|`com.jetbrains.pycharm.ce`
|PyCharm Professional|`com.jetbrains.pycharm`
|QuickTime Player|`com.apple.QuickTimePlayerX`
|Reminders|`com.apple.reminders`
|Safari|`com.apple.Safari`
|Shortcuts|`com.apple.shortcuts`
|Slack|`com.tinyspeck.slackmacgap`
|Spotify|`com.spotify.client`
|Steam|`com.valvesoftware.steam`
|Stocks|`com.apple.stocks`
|Sublime Merge|`com.sublimemerge`
|Sublime Text|`com.sublimetext.4`
|System Settings|`com.apple.systempreferences`
|Telegram|`com.tdesktop.Telegram`
|Terminal|`com.apple.Terminal`
|TextEdit|`com.apple.TextEdit`
|Thunderbird|`org.mozilla.thunderbird`
|Time Machine|`com.apple.backup.launcher`
|Todoist|`com.todoist.mac.Todoist`
|Tor Browser|`org.torproject.torbrowser`
|Transmission|`org.m0k.transmission`
|TV|`com.apple.TV`
|Visual Studio Code|`com.microsoft.VSCode`
|VLC|`org.videolan.vlc`
|VoiceMemos|`com.apple.VoiceMemos`
|VoiceOver Utility|`com.apple.VoiceOverUtility`
|Weather|`com.apple.weather`
|WezTerm|`com.github.wez.wezterm`
|Xcode|`com.apple.dt.Xcode`
|Zen Browser|`app.zen-browser.zen`

|===
